### ISSUE TITLE
Support `drafts.customMedia`

### ISSUE THREAD

**Issue by paulrobertlloyd** [5t3ph/eleventy-plugin-lightningcss#2]
Great plug-in! I’ve got something very similar running on my own site, but would love to defer the complexity to a plugin like this one. And I can… almost! It seems the [`drafts.customMedia`](https://lightningcss.dev/transpilation.html#custom-media-queries) option isn’t supported; can it be?

**Comment by 5t3ph** [comment]
@paulrobertlloyd added in v1.1.0, available now!

**Comment by paulrobertlloyd** [comment]
Blimey, that was quick! Thanks Stephanie 😄
