### ISSUE TITLE
eleventy.js

### ISSUE THREAD

**Issue by DanyJack** [5t3ph/eleventy-plugin-lightningcss#3]
Hi Stephanie ,

Daniele here 👋
Thank you for your plugin. 
I had a problem, I think that setting it with the new configuration file "eleventy.config.js" it doesn’t work, I had to reuse the old name "eleventy.js". 

Could it be, or is it a my problem of other configurations?

Thanks for your check!

**Comment by 5t3ph** [comment]
Hi @DanyJack - I've used the new name on a couple of projects with this plugin and have had it run successfully. Let me know if you got it figured out!
