### ISSUE TITLE
Editing _partial files does not rebuild main stylesheets that import them

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [5t3ph/eleventy-plugin-lightningcss#4]
Hi, thanks for publishing this plugin!

I'm running into a problem that I think may be related to the changes in Eleventy 2.0 to track layout dependencies and only rebuild files that changed. Apologies in advance if this is documented somewhere (I didn't see anything mentioned in the README or in LightningCSS's own docs).

It seems that files output via transforms/plugins don't track dependencies correctly, so if a stylesheet depends on a partial and the partial changes, the stylesheet will not rebuild. I've put together a very minimal repro sandbox here: https://github.com/AleksandrHovhannisyan/11ty-sandbox/tree/eleventy-plugin-lightningcss

To reproduce:

1. Clone that repo.
2. Run `yarn` to install dependencies.
3. Run `yarn serve` to start the 11ty server.
4. Navigate to localhost:8080 to view the site.
5. Edit `src/css/_partial.css` to trigger a rebuild. Observe that the change is detected but `src/css/styles.css` (which depends on `src/css/_partial.css`) does not rebuild.

![Terminal output of running yarn serve: $ npx @11ty/eleventy --serve --incremental
[11ty] Writing _site/src/index.html from ./src/index.html (liquid)
[11ty] Writing _site/src/css/styles.css from ./src/css/styles.css
[11ty] Wrote 2 files in 0.10 seconds (v2.0.1)
[11ty] Watching…
[11ty] Server at http://localhost:8080/
[11ty] File changed: src/css/_partial.css
[11ty] Wrote 0 files (skipped 2) in 0.01 seconds (v2.0.1)
[11ty] Watching…](https://github.com/5t3ph/eleventy-plugin-lightningcss/assets/19352442/4b32bd98-c725-40d8-8492-7e6e86284e97)

Expected behavior: editing `_partial.css` should trigger a rebuild of `styles.css`.

**Comment by AleksandrHovhannisyan** [comment]
Just following up on this to see if there's anything I missed. I couldn't find anything about it in the LightningCSS docs or in this plugin's docs.

My guess as to what is happening is that when I edit `src/css/_partial.css`, it hits this check and early returns:

https://github.com/5t3ph/eleventy-plugin-lightningcss/blob/0247184835916ef224a4c6e562932531100fa6ef/.eleventy.js#L78-L80

Which makes sense since we don't want to compile that partial, but what we _do_ want is to compile any stylesheet that imports this partial.

---

Conceptually, the solution I'm thinking of is to make some sort of dependency graph so that when we run `compile` on a partial, we can look up all stylesheets that import that partial and compile those files.

**Comment by julientaq** [comment]
hey, i think i found a way to make it work.

https://gist.github.com/julientaq/c777293b098ed802936eff7420ad6efbG

i’m using the addDependencies that eleventy offers to link the css files between them. 
if i find a @import in a css file, it will add the link to the import as a dependency of the css file.


i’m doing it like this: 

```js
  // set @import dependencies for each url that contains @import
      if (_inputContent.includes("@import")) {
        // for each file create a list of files to look at
        const fileList = [];

        // get a list of import on the file your reading
        const importRuleRegex =
          /@import\s+(?:url\()?['"]?([^'"\);]+)['"]?\)?.*;/g;

        let match;
        while ((match = importRuleRegex.exec(_inputContent))) {
          fileList.push(parsed.dir + "/" + match[1]);
        }

        this.addDependencies(inputPath, fileList);
      }
 ```
 
 please note that this may come untested outside of a specific css folders set up.
 
 ---

eleventy is magic.

@5t3ph you may want to add this bit to your amazing plugin, which put me on the right path :D.

Thanks for all the work you do around eleventy and all, always full of inspiration.


@AleksandrHovhannisyan would you mind testing that?

**Comment by 5t3ph** [comment]
@julientaq @AleksandrHovhannisyan thanks for the investigation and fix! Please try out v1.2.0 or higher and let me know if you still encounter an issue or if we can resolve

**Comment by julientaq** [comment]
all good on my end. Thanks!

**Comment by AleksandrHovhannisyan** [comment]
Sorry that it took me so long to get back to you on this; yes, that change fixed the issue. Thanks!
